version: '3.9'

services:

  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=dev-js
      - NODE_PORT=3000
    volumes:
      - .:/app

  api_postgres:
    container_name: api_postgres
    build: .
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=dev-postgres
      - NODE_PORT=3001
    volumes:
      - .:/app_postgres      

  database:
    container_name: database
    image: postgres:14.3
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_postgres:/var/lib/postgresql/data

volumes:
  db_postgres:
    driver: local